apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRole
metadata:
  name: composite-controller-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true" 
    rbac.authorization.k8s.io/aggregate-to-edit: "true" 
rules:
  - apiGroups: ["crd.example.com"]
    resources: ["Composition", "compositions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
  - apiGroups: ["apps"]
    resources: ["Deployment", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["Event", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: composite-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: composite-controller-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default