apiVersion: apps/v1
kind: Deployment
metadata:
  name: composite-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composite
  template:
    metadata:
      labels:
        app: composite
    spec:
      containers:
      - name: composite
        image: "vipinpsc/composite-controller:latest"