apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compositions.crd.example.com
spec:
  group: crd.example.com
  version: v1alpha1
  names:
    kind: Composition
    plural: compositions
  scope: Namespaced
  subresources:
    status: {}
