apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compositions.crd.example.com
spec:
  group: crd.example.com
  version: v1alpha1
  names:
    kind: Composition
    plural: compositions
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 50
